### ISSUE TITLE
dev4 docker config needs adjusting to avoid root partition filling up

### ISSUE THREAD

**Issue by donalhunt** [osmie/openstreetmapIE#7]
@jpronans alerted me to the fact that the "/" partition on dev4 is filling up after I deployed docker and started some containers to support the website revamp work @tadcan is doing.

The work is fairly trivial:
- stop docker containers.
- stop docker service
- move data in /var/data/docker (tbc) to a partition with space (need to review which disk is preferred)
- configure docker to use the new location (-g flag)
- restart docker service
- restart containers.

I found some guides (common issue) so will like them when I get a chance.

**Comment by jpronans** [comment]
looking at this now. Plan is to put a 40GB partition into /var/lib/docker, move file files back in there when done.

**Comment by jpronans** [comment]
You might need to restart the containers.

**Comment by donalhunt** [comment]
containers that were running for @tadcan's wordpress testing are up and running again. \o/
think we can call this one closed (though /dev/vda1 still looks a little full).

thoughts @jpronans?

**Comment by jpronans** [comment]
I still had the original docker files on /dev/vda1. Now that you verified that docker was ok.. I've removed them.

**Comment by donalhunt** [comment]
Going to close this out since filesystems look healthy now. :)

```bash
/dev/vda1       9.6G  5.0G  4.6G  53% /
/dev/vdf         47G  3.7G   41G   9% /var/lib/docker
```

```bash
# du -sh /var --exclude /var/lib/docker
1.9G	/var
```
